-- MySQL Script generated by MySQL Workbench
-- Fri Dec 11 11:07:24 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema kaeseshop
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema kaeseshop
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `kaeseshop` DEFAULT CHARACTER SET utf8 ;
USE `kaeseshop` ;

-- -----------------------------------------------------
-- Table `kaeseshop`.`sort`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`sort` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `sortName` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `kaeseshop`.`price`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`price` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `pricePerUnit` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `kaeseshop`.`specifics`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`specifics` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `taste` VARCHAR(1) NOT NULL DEFAULT 'LIKE (M,W)',
  `lactose` TINYINT(1) NOT NULL,
  `milkType` VARCHAR(1) NULL DEFAULT 'LIKE(B,K,S,Z)',
  `rawMilk` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `kaeseshop`.`cheese`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`cheese` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `cheeseName` VARCHAR(45) NOT NULL,
  `sort_id`  NOT NULL,
  `price_id`  NOT NULL,
  `specifics_id`  NOT NULL,
  `qtyInStock` INT NOT NULL,
  `descrip` LONGTEXT NOT NULL,
  `recipe` LONGTEXT NULL,
  PRIMARY KEY (`id`, `sort_id`, `price_id`, `specifics_id`),
  INDEX `fk_cheese_sort_idx` (`sort_id` ASC) VISIBLE,
  INDEX `fk_cheese_price1_idx` (`price_id` ASC) VISIBLE,
  INDEX `fk_cheese_specifics1_idx` (`specifics_id` ASC) VISIBLE,
  CONSTRAINT `fk_cheese_sort`
    FOREIGN KEY (`sort_id`)
    REFERENCES `kaeseshop`.`sort` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cheese_price1`
    FOREIGN KEY (`price_id`)
    REFERENCES `kaeseshop`.`price` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cheese_specifics1`
    FOREIGN KEY (`specifics_id`)
    REFERENCES `kaeseshop`.`specifics` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `kaeseshop`.`address`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`address` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `zipCode` VARCHAR(5) NOT NULL DEFAULT 'LIKE ([0-9][0-9][0-9][0-9][0-9])',
  `city` VARCHAR(50) NOT NULL,
  `strNo` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `kaeseshop`.`account`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`account` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `firstName` VARCHAR(45) NOT NULL,
  `lastName` VARCHAR(45) NOT NULL,
  `address_id`  NOT NULL,
  `payMethod` VARCHAR(1) NULL DEFAULT 'Like(P,B,S)',
  `isAdmin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`, `address_id`),
  INDEX `fk_account_address1_idx` (`address_id` ASC) VISIBLE,
  CONSTRAINT `fk_account_address1`
    FOREIGN KEY (`address_id`)
    REFERENCES `kaeseshop`.`address` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `kaeseshop`.`date`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`date` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `date` DATE NOT NULL,
  PRIMARY KEY (`id`));


-- -----------------------------------------------------
-- Table `kaeseshop`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`orders` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `account_id`  NOT NULL,
  `shipingDate`  NULL,
  PRIMARY KEY (`id`, `account_id`),
  INDEX `fk_orders_account1_idx` (`account_id` ASC) VISIBLE,
  INDEX `fk_orders_date2_idx` (`shipingDate` ASC) VISIBLE,
  CONSTRAINT `fk_orders_account1`
    FOREIGN KEY (`account_id`)
    REFERENCES `kaeseshop`.`account` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orders_date2`
    FOREIGN KEY (`shipingDate`)
    REFERENCES `kaeseshop`.`date` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


-- -----------------------------------------------------
-- Table `kaeseshop`.`orderedItems`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `kaeseshop`.`orderedItems` (
  `id`  NOT NULL,
  `createdAt` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updatetAt` TIMESTAMP NULL DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
  `cheese_id`  NOT NULL,
  `quantity` INT NOT NULL,
  `actualPrice` DECIMAL(7,2) NOT NULL,
  `orders_id`  NOT NULL,
  PRIMARY KEY (`id`, `cheese_id`, `orders_id`),
  INDEX `fk_orderedItems_cheese1_idx` (`cheese_id` ASC) VISIBLE,
  INDEX `fk_orderedItems_orders1_idx` (`orders_id` ASC) VISIBLE,
  CONSTRAINT `fk_orderedItems_cheese1`
    FOREIGN KEY (`cheese_id`)
    REFERENCES `kaeseshop`.`cheese` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orderedItems_orders1`
    FOREIGN KEY (`orders_id`)
    REFERENCES `kaeseshop`.`orders` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
